# Generated by Django 3.2.16 on 2023-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinets',
            name='ready',
            field=models.IntegerField(default=0, verbose_name='Готовность'),
        ),
    ]
