# Generated by Django 3.2.16 on 2023-02-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_cabinets_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signals',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Сигналы'),
        ),
    ]
